name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: |
        npm install
        npm install -D webpack-cli  # Установка webpack-cli

    - name: Build
      run: |
        npm audit fix --force
        npm install
        npx webpack
        
    - name: Clone the deployment repository
      run: |
        git clone https://github.com/tedfak/svgsmsc-site.git svgsmsc-site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy files to deployment repository
      run: |
        rm -rf svgsmsc-site/*  # Очистим старые файлы в репозитории
        cp -R build/* svgsmsc-site/  # Копируем сборку в репозиторий

    # Шаг 6: Коммит и пуш изменений в репозиторий для деплоя
    - name: Commit and push changes
      run: |
        cd svgsmsc-site
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"
        git add .
        git commit -m "Automated deployment"
        git push origin main
      env:
        # Добавляем секрет с токеном доступа
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
